### ISSUE TITLE
use Riot Tag or Jade Template?

### ISSUE THREAD

**Issue by crapthings** [yavorsky/riot-brunch#6]
```
  plugins:
    on: ["riot"]
    riot:
      extension: 'tag'   # pattern overrides extension
      pattern: /\.tag$/  # default
      template: 'jade'
      type: 'coffeescript'
```

config template is using jade

is that mean write jade and coffeescript in template.tag ?
